### ISSUE TITLE
As an automated process, the application should deploy itself in real time

### ISSUE THREAD

**Issue by varunsinghal** [varunsinghal/noteware#24]
**User Story**
As an automated process, the application should deploy itself in real time.

**Story points** 3

**Priority** 1

**Tasks**
- [x] Enable real time deployment #22 
- [ ] Separate settings.py #38 

**Bugs**
- [x] Bug: allowed host : noteware.herokuapp.com #25 
- [x] Bug: missing static files #27
- [x] Bug: migrations in heroku deployment #37 
- [x] Bug: Missed out requirments - requests #36
