### ISSUE TITLE
As a guest user, I want to click on google auth so that I can login to the application.

### ISSUE THREAD

**Issue by varunsinghal** [varunsinghal/noteware#5]
**User Story**
As a guest user, I want to click on google auth so that I can log in to the application.

**Story points** 5

**Priority** 4

**Task**
- [ ] Add google authorization button
- [ ] Start session of the authorized user
- [ ] display profile page
