### ISSUE TITLE
As a user, I want to upload notes so that they are stored in the cloud.

### ISSUE THREAD

**Issue by varunsinghal** [varunsinghal/noteware#9]
**User Story**
As a user, I want to upload notes so that they are stored in the cloud.

**Story points** 10

**Priority** 7

**Tasks**
- [ ] Upload form
- [ ] Add new course
- [ ] Add new branch
- [ ] Add new professor
- [ ] Select multiple files
- [ ] My uploads list
